spring:
  thymeleaf:
    mode: HTML5
    cache: false

dubbo:
  application:
    name: myshop_back
  registry:
    address: zookeeper://192.168.152.133:2181
fdfs:
#  连接超时时间
  connect-timeout: 60
  pool:
    jmx-enabled: false
#    缩略图
  thumb-image:
    height: 200
    width: 200
#    track服务配置地址列表
  tracker-list: 192.168.152.133:22122
#  图片路径前缀
image:
  path: http://192.168.152.133/