server:
  port: 8086
spring:
  thymeleaf:
    cache: false
  redis:
    host: 192.168.152.133
    password: 123456
dubbo:
  application:
    name: myshop_order
  registry:
    address: zookeeper://192.168.152.133:2181
    timeout: 2000
  consumer:
    check: false
logging:
  level:
    root: debug