server:
  port: 8082
dubbo:
  application:
    name: myshop_search
  registry:
    address: zookeeper://192.168.152.133:2181
    timeout: 2000
  consumer:
    check: false


#  图片路径前缀
image:
  path: http://192.168.152.133/